### ISSUE TITLE
Loading Maps

### ISSUE THREAD

**Issue by aabanaag** [flyandi/mazda-enhanced-compass#2]
I followed the steps but what I did was apply it via ssh. But when I tried to load the SD Card it is stucked on Loading Maps and nothing happens right after. Is there anything I'm missing? Also we did tried to load the map for Manila, Philippines

**Comment by flyandi** [comment]
Can you post a picture please so I can see what issue it might be.

Usually these errors are related to no proper symlinking

**Comment by aabanaag** [comment]
Ok I'll post a picture. But its a dialog with Loading maps and a activity indicator beneath it. Also I noticed that on the steps provided it was stated that apply the symlink? but on my case there was no /tmp/mnt/sd_nav folder also the /jci/gui/apps/emnavi/controls/Compass/resources folder is not there so I went ahead and applied the command then rebooted the car fired up navigation, the insert SD card prompt showed (or even if it doesn't) it would just prompt the Loading Maps dialog.

**Comment by flyandi** [comment]
Ok - then it won't work. What system software do you have in your Mazda?

**Comment by aabanaag** [comment]
What do you mean by system software? Is that the version?

**Comment by aabanaag** [comment]
but when I inserted a SDcard the tmp/mnt/sd_nav if now existing but I havent checked the /jci/gui/apps/emnavi/controls/Compass/resources folder though.

**Comment by flyandi** [comment]
Your Mazda runs a certain version of the base system. This app supports version 27.x and higher. 

yeah, the /tmp/mnt/sd_nav only exists if you put the sd card into it. As long you symlink the resource folder and have insert the card it should work.

ln -s /tmp/mnt/sd_nav /jci/gui/apps/emnavi/controls/Compass/resources

Now I remember that someone in Poland had an issue like you have because your local Mazda implementation is different (license restrictions from NavTeq, etc) but I also know that some people in the Phillipines are using it successfully.

You might have an outdated system software.

**Comment by aabanaag** [comment]
How would I check if I have an outdated software? My system version V28

**Comment by aabanaag** [comment]
Your Mazda runs a certain version of the base system. This app supports version 27.x and higher.

yeah, the /tmp/mnt/sd_nav only exists if you put the sd card into it. As long you symlink the resource folder and have insert the card it should work.

ln -s /tmp/mnt/sd_nav /jci/gui/apps/emnavi/controls/Compass/resources

Now I remember that someone in Poland had an issue like you have because your local Mazda implementation is different (license restrictions from NavTeq, etc) but I also know that some people in the Phillipines are using it successfully.

You might have an outdated system software.

**Comment by aabanaag** [comment]
Also I don't get it. These path /jci/gui/apps/emnavi/controls/Compass/resources really doesn't exist right? even from the jci folder of the released version. Should I create the resource folder then for the symlink to work?

**Comment by flyandi** [comment]
No that path is the symlink, you symlink ..resources/ to the path on the sd card:

ln -s /tmp/mnt/sd_nav /jci/gui/apps/emnavi/controls/Compass/resources

**Comment by aabanaag** [comment]
Oh okay. Is it about the maps? I did tried to generate tiles using the manila osm.pdb type but what I did was at first the I deleted the contents of the tile folder from the released package and copied the generated tile when it didn't worked I copied the tile folder from the release package then copied the generated files onto the designated folders.

Should I update my version to the latest version?

**Comment by flyandi** [comment]
start with the world pack found in the tile downloads. Get that to work before you going to install a third party tile pack.

Just to make sure, the SD Card contains all the primary program as described in the setup instructions? right?

**Comment by aabanaag** [comment]
Ok. yes. I copied everything from the SDCard folder of the release package. Will try to work it out. Thank you so much!

**Comment by aabanaag** [comment]
So basically I did tried it out. Followed the instructions

I reformatted the SD card to Fat32.
copied the sdcard directory from dist/ (from cloned repo)
download world.7z extracted it and copied it over to sdcard/tiles directory
ssh into the device and remove the symlink and added it again

I got confused with the terminology but the error was Loading Navigation not Loading Maps. sorry bout that.. Anyways you mentioned NavTeq is there something I should do?

**Comment by flyandi** [comment]
Can you take a picture of it please. I think I know whats going on and I don't know if there is a solution for that.  It seems some old implementations like 28.x don't continue to load the compass application if an "non Mazda" sd-card is detected. 

If you remove the SD-Card, do you get the compass application?

I know a lot of stuff changed since 33.x - so if the best and easiest way would be to upgrade at least to 33.x preferable of course to 55.x

**Comment by aabanaag** [comment]
here is the links

https://www.dropbox.com/s/51kj245s0c2e12e/IMG_0861.jpg?dl=0
https://www.dropbox.com/s/1zh2wtxo11t5gri/IMG_0862.jpg?dl=0

Also when I remove the SD-card I get the Insert SD card message

**Comment by flyandi** [comment]
Yep - exactly what I thought. I have seen this twice already with older versions. 

You need to upgrade to at least 33.x - basically what happens is that the system fails to realize that it is a "invalid" sd card and move on to load the Compass app regardless. It's stuck. All the new system have that implemented.

The good news is that you did everything right but you need to  Update, Update, Update :-)

**Comment by aabanaag** [comment]
Okay. Thank you soo much for patiently answering my questions. I'll let you know once I successfully loaded everything. Also once I did, my team and I would love to contribute to this wonderful project. 

Again Thank you.

**Comment by flyandi** [comment]
Anytime! :-)

**Comment by aabanaag** [comment]
Hi I know its already closed. But I updated to v.51 I got the loading Navigation it disappeared after then says Invalid SD Card.

**Comment by flyandi** [comment]
Ok good. Can you post a screenshot of the root contents of the SD Card as well what you see on the Infotainment system?

**Comment by aabanaag** [comment]
Apparently I have made mistakes following the steps. I reverted to the old copy then I no longer get the invalid sd card. But the map is not rendering its just blank also there is an instance that the map is rendered but no Lat,Long and Elevation data

**Comment by aabanaag** [comment]
Link to screenshot of the root contents of the SD Card:
https://www.dropbox.com/s/nn07of308gmhvn3/Screenshot%202015-10-13%2023.15.44.png?dl=0

Link to screenshot of the actual infotainment
https://www.dropbox.com/s/afe9rlus001e8uf/IMG_0876.jpg?dl=0
https://www.dropbox.com/s/svsand37cm4nyrz/2015-10-13%2023.25.14.jpg?dl=0

**Comment by aabanaag** [comment]
Hey I took it for a spin and it worked. I just got issues with the map when zoomed in its blurry. Also when connecting my iPhone and someone called me the infotainment froze and needed a restart. I'll have it opened in the forums though. Thank you soo much. Looking forward for the upcoming releases!

**Comment by flyandi** [comment]
Oh the blurriness is due to tiles missing. Did you put the world pack on it? The world pack contains zoom levels 1 - 10 which covers at least in high level most major road networks.

For detail you need to install the pack for your country.

**Comment by aabanaag** [comment]
So just to clarify I need to have the Base pack then include the Manila map?

Also I noticed the world.7z contains only 0-6 and the generated tile for manila is 9-13. Will there be a issue since 7-8 are missing?

**Comment by flyandi** [comment]
Yep that's correct. 

If you included zoom levels 0-6 in your Manila pack than you are good to go, too. But I already created the world map, so no need to create that again :-)

https://github.com/flyandi/mazda-enhanced-compass/wiki/Tiles

Download the base pack from zoom level 0-6 and merge it with your manila map tiles.

**Comment by aabanaag** [comment]
"But I already created the world map, so no need to create that again :-)"

Is it the once included in the release version? The release version has 0-10 so if I have 9-13 the contents of 9-10 (manila map) should be merged to the 9-10 folders of the release version?

Also do I have to generate my map to have zoom levels 0-10? because currently the levels are set to 9-13.
