### ISSUE TITLE
Does this work for 2014 Mazda 6's?

### ISSUE THREAD

**Issue by jch** [flyandi/mazda-enhanced-compass#5]
I'm not sure how to check the version number, and the information linked from the wiki sounds like this was designed for Mazda 3's. Just wanted to double check in case it is compatible.

**Comment by flyandi** [comment]
This only runs on the 3rd gen 6's - so 2016+ 

The funny thing is that most people are using it on the Mazda 3 however I built it using my 2016 Mazda 6 :-)

**Comment by jch** [comment]
Thanks for the info!
